/-
Copyright (c) 2026 Daniel Hofheinz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Hofheinz
-/
import CivicAlignment.PaperII.EscapeWindow
import Mathlib.Data.Real.ENatENNReal
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Process.HittingTime

/-!
# Paper II: the infinite Gaussian saddle-crossing process

This file supplies the probability space and stopping-time layer needed for the
staged Arrhenius upgrade of `conj:arr`.  The coordinate process lives on the
canonical countable product of standard real Gaussians.  Its finite prefixes
are proved to have exactly the law used by `EscapeWindow`, so the finite-window
large-deviation estimates and the eventual mean first-crossing time concern
the same recursion. The legacy `Escape` names in this module refer to this
saddle-policy crossing event, not to exit from the calibrated basin.
-/

namespace CivicAlignment.PaperII

open Filter Function MeasureTheory ProbabilityTheory Set Topology
open scoped ENNReal NNReal

noncomputable section

/-! ## Canonical i.i.d. Gaussian histories -/

/-- Infinite histories of real standard-Gaussian coordinates. -/
abbrev GaussianNoisePath := ℕ → ℝ

/-- The canonical law of an infinite i.i.d. standard-Gaussian history. -/
def standardGaussianSequence : Measure GaussianNoisePath :=
  Measure.infinitePi fun _ : ℕ ↦ gaussianReal 0 1

instance : IsProbabilityMeasure standardGaussianSequence := by
  unfold standardGaussianSequence
  infer_instance

/-- Restriction of an infinite noise history to its first `T` coordinates. -/
def gaussianPrefix (T : ℕ) (xi : GaussianNoisePath) : Fin T → ℝ :=
  fun i ↦ xi i

/-- Every finite prefix of the canonical sequence has exactly the finite
product law used in `EscapeWindow`. -/
theorem standardGaussianSequence_map_prefix (T : ℕ) :
    standardGaussianSequence.map (gaussianPrefix T) =
      standardGaussianVector T := by
  unfold standardGaussianSequence standardGaussianVector gaussianPrefix
  calc
    (Measure.infinitePi fun _ : ℕ ↦ gaussianReal 0 1).map
        (fun xi : ℕ → ℝ ↦ fun i : Fin T ↦ xi (i : ℕ)) =
        Measure.infinitePi (fun _ : Fin T ↦ gaussianReal 0 1) :=
      Measure.map_infinitePi_infinitePi_of_inj
        (P := fun _ : ℕ ↦ gaussianReal 0 1)
        (f := fun i : Fin T ↦ (i : ℕ)) Fin.val_injective
    _ = Measure.pi (fun _ : Fin T ↦ gaussianReal 0 1) :=
      Measure.infinitePi_eq_pi (fun _ : Fin T ↦ gaussianReal 0 1)

/-- Prefix restriction is measurable for the product measurable spaces. -/
theorem measurable_gaussianPrefix (T : ℕ) : Measurable (gaussianPrefix T) := by
  exact measurable_pi_iff.2 fun i ↦ measurable_pi_apply (i : ℕ)

/-- The infinite noise history after discarding its first `N` coordinates. -/
def gaussianTail (N : ℕ) (xi : GaussianNoisePath) : GaussianNoisePath :=
  fun n ↦ xi (N + n)

/-- Every deterministic tail of the canonical i.i.d. Gaussian sequence has
the same law as the original sequence. -/
theorem standardGaussianSequence_map_tail (N : ℕ) :
    standardGaussianSequence.map (gaussianTail N) =
      standardGaussianSequence := by
  unfold standardGaussianSequence gaussianTail
  exact Measure.map_infinitePi_infinitePi_of_inj
    (P := fun _ : ℕ ↦ gaussianReal 0 1)
    (f := fun n : ℕ ↦ N + n)
    (fun _a _b h ↦ Nat.add_left_cancel h)

/-- Tail restriction is measurable on the product measurable space. -/
theorem measurable_gaussianTail (N : ℕ) : Measurable (gaussianTail N) := by
  exact measurable_pi_iff.2 fun n ↦ measurable_pi_apply (N + n)

/-- Measuring any measurable event after a deterministic tail shift gives
the same probability. -/
theorem standardGaussianSequence_tail_preimage
    (N : ℕ) {s : Set GaussianNoisePath} (hs : MeasurableSet s) :
    standardGaussianSequence (gaussianTail N ⁻¹' s) =
      standardGaussianSequence s := by
  rw [← Measure.map_apply (measurable_gaussianTail N) hs,
    standardGaussianSequence_map_tail]

/-! ## The noisy recursion and its finite prefixes -/

/-- The clipped civic-weighted recursion driven by the controls `sigma * xi_t`,
starting at the calibrated state. -/
def gaussianNoisyOrbit (p : LoopParams) (rho sigma : ℝ)
    (xi : GaussianNoisePath) : ℕ → LoopState
  | 0 => calibratedPoint p
  | n + 1 => controlledCivicWeightedStep p rho (sigma * xi n)
      (gaussianNoisyOrbit p rho sigma xi n)

/-- The noisy orbit is the controlled path generated by its scaled noise
coordinates. -/
theorem gaussianNoisyOrbit_isControlled (p : LoopParams) (rho sigma : ℝ)
    (xi : GaussianNoisePath) :
    IsControlledCivicWeightedPath p rho (fun n ↦ sigma * xi n)
      (gaussianNoisyOrbit p rho sigma xi) where
  initial := rfl
  step _ := rfl

/-- At every fixed time the noisy state is a continuous function of the
infinite coordinate history. -/
theorem continuous_gaussianNoisyOrbit (p : LoopParams) (rho sigma : ℝ)
    (n : ℕ) :
    Continuous (fun xi : GaussianNoisePath ↦ gaussianNoisyOrbit p rho sigma xi n) := by
  induction n with
  | zero =>
      simp only [gaussianNoisyOrbit]
      fun_prop
  | succ n ih =>
      simp only [gaussianNoisyOrbit]
      unfold controlledCivicWeightedStep civicWeightedGradient
        LoopParams.gradU LoopParams.stockStep LoopParams.s LoopParams.clipUnit
      fun_prop

/-- Fixed-time noisy states are strongly measurable. -/
theorem stronglyMeasurable_gaussianNoisyOrbit (p : LoopParams) (rho sigma : ℝ)
    (n : ℕ) :
    StronglyMeasurable
      (fun xi : GaussianNoisePath ↦ gaussianNoisyOrbit p rho sigma xi n) :=
  (continuous_gaussianNoisyOrbit p rho sigma n).stronglyMeasurable

/-- The natural filtration generated by the noisy state process. -/
def gaussianOrbitFiltration (p : LoopParams) (rho sigma : ℝ) :
    Filtration ℕ (inferInstance : MeasurableSpace GaussianNoisePath) :=
  Filtration.natural (fun n xi ↦ gaussianNoisyOrbit p rho sigma xi n)
    (stronglyMeasurable_gaussianNoisyOrbit p rho sigma)

/-- The noisy recursion is adapted to its natural filtration. -/
theorem gaussianNoisyOrbit_adapted (p : LoopParams) (rho sigma : ℝ) :
    Adapted (gaussianOrbitFiltration p rho sigma)
      (fun n xi ↦ gaussianNoisyOrbit p rho sigma xi n) := by
  unfold gaussianOrbitFiltration
  exact (Filtration.stronglyAdapted_natural
    (stronglyMeasurable_gaussianNoisyOrbit p rho sigma)).adapted

/-- Through time `n ≤ T`, the infinite recursion agrees with the finite-prefix
recursion used by `EscapeWindow`. -/
theorem gaussianNoisyOrbit_eq_finiteControlledOrbit (p : LoopParams)
    (rho sigma : ℝ) (xi : GaussianNoisePath) {T n : ℕ} (hn : n ≤ T) :
    gaussianNoisyOrbit p rho sigma xi n =
      finiteControlledOrbit p rho
        (scaledGaussianControl sigma (gaussianPrefix T xi)) n := by
  induction n with
  | zero => rfl
  | succ n ih =>
      have hnlt : n < T := by omega
      rw [gaussianNoisyOrbit, finiteControlledOrbit, ih (by omega)]
      simp only [scaledGaussianControl, gaussianPrefix, extendFiniteControl,
        hnlt, dite_true]

/-! ## Finite crossing events on the infinite history space -/

/-- A running maximum exceeds a level exactly when one of the observations up
to that time exceeds it. -/
theorem le_runningMax_iff {a : ℕ → ℝ} {c : ℝ} {n : ℕ} :
    c ≤ runningMax a n ↔ ∃ k ≤ n, c ≤ a k := by
  induction n with
  | zero => simp only [runningMax_zero, Nat.le_zero, exists_eq_left]
  | succ n ih =>
      rw [runningMax_succ, le_max_iff, ih]
      constructor
      · rintro (⟨k, hk, hck⟩ | hlast)
        · exact ⟨k, hk.trans n.le_succ, hck⟩
        · exact ⟨n + 1, le_rfl, hlast⟩
      · rintro ⟨k, hk, hck⟩
        rcases Nat.lt_or_eq_of_le hk with hklt | rfl
        · exact Or.inl ⟨k, Nat.le_of_lt_succ hklt, hck⟩
        · exact Or.inr hck

/-- The policy running maximum of a finite controlled orbit depends
continuously on its finite control vector. -/
theorem continuous_policyRunningMax_finiteControlledOrbit (p : LoopParams)
    (rho : ℝ) {T : ℕ} (n : ℕ) :
    Continuous (fun u : Fin T → ℝ ↦
      policyRunningMax (finiteControlledOrbit p rho u) n) := by
  induction n with
  | zero =>
      simpa only [policyRunningMax, runningMax_zero] using
        (continuous_finiteControlledOrbit p rho (T := T) 0).fst
  | succ n ih =>
      simpa only [policyRunningMax, runningMax_succ] using
        ih.max (continuous_finiteControlledOrbit p rho (T := T) (n + 1)).fst

/-- The policy running maximum of the infinite noisy orbit depends
continuously on the coordinate history. -/
theorem continuous_policyRunningMax_gaussianNoisyOrbit (p : LoopParams)
    (rho sigma : ℝ) (n : ℕ) :
    Continuous (fun xi : GaussianNoisePath ↦
      policyRunningMax (gaussianNoisyOrbit p rho sigma xi) n) := by
  induction n with
  | zero =>
      simpa only [policyRunningMax, runningMax_zero] using
        (continuous_gaussianNoisyOrbit p rho sigma 0).fst
  | succ n ih =>
      simpa only [policyRunningMax, runningMax_succ] using
        ih.max (continuous_gaussianNoisyOrbit p rho sigma (n + 1)).fst

/-- The event that the infinite noisy recursion has crossed the weighted saddle
by time `T`. -/
def gaussianEscapeByEvent {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    Set GaussianNoisePath :=
  {xi | weighted.βdagger ≤
    policyRunningMax (gaussianNoisyOrbit p rho sigma xi) T}

/-- The finite-prefix crossing event is Borel measurable. -/
theorem measurableSet_gaussianEscapeEvent {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    MeasurableSet (gaussianEscapeEvent weighted T sigma) := by
  change MeasurableSet ((fun xi : Fin T → ℝ ↦
    policyRunningMax
      (finiteControlledOrbit p rho (scaledGaussianControl sigma xi)) T) ⁻¹'
        Ici weighted.βdagger)
  apply measurableSet_Ici.preimage
  exact (continuous_policyRunningMax_finiteControlledOrbit p rho T).measurable.comp
    (by unfold scaledGaussianControl; fun_prop)

/-- The infinite-history crossing event is Borel measurable. -/
theorem measurableSet_gaussianEscapeByEvent {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    MeasurableSet (gaussianEscapeByEvent weighted T sigma) := by
  change MeasurableSet ((fun xi : GaussianNoisePath ↦
    policyRunningMax (gaussianNoisyOrbit p rho sigma xi) T) ⁻¹'
      Ici weighted.βdagger)
  exact measurableSet_Ici.preimage
    (continuous_policyRunningMax_gaussianNoisyOrbit p rho sigma T).measurable

/-- Pulling the finite crossing event back along prefix restriction gives the
crossing event for the actual infinite recursion. -/
theorem gaussianPrefix_preimage_escapeEvent {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    gaussianPrefix T ⁻¹' gaussianEscapeEvent weighted T sigma =
      gaussianEscapeByEvent weighted T sigma := by
  ext xi
  simp only [mem_preimage, gaussianEscapeEvent, gaussianEscapeByEvent,
    mem_setOf_eq]
  have hmax :
      policyRunningMax
          (finiteControlledOrbit p rho
            (scaledGaussianControl sigma (gaussianPrefix T xi))) T =
        policyRunningMax (gaussianNoisyOrbit p rho sigma xi) T := by
    apply le_antisymm
    · apply runningMax_le_of_forall_le
      intro k hk
      rw [← gaussianNoisyOrbit_eq_finiteControlledOrbit p rho sigma xi hk]
      exact (policy_le_runningMax (gaussianNoisyOrbit p rho sigma xi) k).trans
        ((monotone_runningMax fun n ↦ (gaussianNoisyOrbit p rho sigma xi n).1) hk)
    · apply runningMax_le_of_forall_le
      intro k hk
      rw [gaussianNoisyOrbit_eq_finiteControlledOrbit p rho sigma xi hk]
      exact (policy_le_runningMax
          (finiteControlledOrbit p rho
            (scaledGaussianControl sigma (gaussianPrefix T xi))) k).trans
        ((monotone_runningMax fun n ↦
          (finiteControlledOrbit p rho
            (scaledGaussianControl sigma (gaussianPrefix T xi)) n).1) hk)
  rw [hmax]

/-- The probability of crossing by `T` in the infinite recursion is exactly
the finite-window probability already formalized in `EscapeWindow`. -/
theorem standardGaussianSequence_escapeByEvent {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    standardGaussianSequence (gaussianEscapeByEvent weighted T sigma) =
      gaussianEscapeProbability weighted T sigma := by
  rw [← gaussianPrefix_preimage_escapeEvent weighted T sigma]
  rw [← Measure.map_apply (measurable_gaussianPrefix T)
    (measurableSet_gaussianEscapeEvent weighted T sigma)]
  rw [standardGaussianSequence_map_prefix]
  rfl

/-! ## First-crossing time and mean first-crossing time -/

/-- The first time the noisy state reaches or crosses the weighted saddle,
with value `top` if it never crosses. -/
def gaussianEscapeTime {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ) :
    GaussianNoisePath → WithTop ℕ :=
  hittingAfter (fun n xi ↦ gaussianNoisyOrbit p rho sigma xi n)
    {x | weighted.βdagger ≤ x.1} 0

/-- The first saddle-crossing time is a stopping time for the natural state
filtration. -/
theorem gaussianEscapeTime_isStoppingTime {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ) :
    IsStoppingTime (gaussianOrbitFiltration p rho sigma)
      (gaussianEscapeTime weighted sigma) := by
  unfold gaussianEscapeTime
  exact (gaussianNoisyOrbit_adapted p rho sigma).isStoppingTime_hittingAfter
    (measurableSet_Ici.preimage measurable_fst)

/-- Crossing by a finite horizon is exactly the corresponding crossing-time
sublevel event. -/
theorem gaussianEscapeTime_le_iff {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ)
    (xi : GaussianNoisePath) (T : ℕ) :
    gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ) ↔
      xi ∈ gaussianEscapeByEvent weighted T sigma := by
  have hhit :
      hittingAfter (fun n xi ↦ gaussianNoisyOrbit p rho sigma xi n)
          {x | weighted.βdagger ≤ x.1} 0 xi ≤ (T : WithTop ℕ) ↔
        ∃ j ∈ Icc 0 T,
          gaussianNoisyOrbit p rho sigma xi j ∈ {x | weighted.βdagger ≤ x.1} :=
    hittingAfter_le_iff
  rw [gaussianEscapeTime, hhit]
  simp only [mem_Icc, zero_le, true_and, mem_setOf_eq,
    gaussianEscapeByEvent]
  exact le_runningMax_iff.symm

/-- The distribution function of the first saddle-crossing time is the finite-window
probability from `EscapeWindow`. -/
theorem standardGaussianSequence_escapeTime_le {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    standardGaussianSequence
        {xi | gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ)} =
      gaussianEscapeProbability weighted T sigma := by
  rw [show {xi | gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ)} =
      gaussianEscapeByEvent weighted T sigma by
    ext xi
    exact gaussianEscapeTime_le_iff weighted sigma xi T]
  exact standardGaussianSequence_escapeByEvent weighted T sigma

/-- The escape-by-`T` probability expressed directly through the infinite
noisy process. -/
def gaussianEscapeTimeProbability {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    ℝ≥0∞ :=
  standardGaussianSequence
    {xi | gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ)}

/-- Its extended-real logarithmic small-noise rate. -/
def gaussianEscapeTimeLogRate {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    EReal :=
  (sigma ^ 2 : ℝ) * ENNReal.log (gaussianEscapeTimeProbability weighted T sigma)

@[simp]
theorem gaussianEscapeTimeProbability_eq {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    gaussianEscapeTimeProbability weighted T sigma =
      gaussianEscapeProbability weighted T sigma :=
  standardGaussianSequence_escapeTime_le weighted T sigma

@[simp]
theorem gaussianEscapeTimeLogRate_eq {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    gaussianEscapeTimeLogRate weighted T sigma =
      gaussianEscapeLogRate weighted T sigma := by
  simp only [gaussianEscapeTimeLogRate, gaussianEscapeLogRate,
    gaussianEscapeTimeProbability_eq]

/-- The fixed-window large-deviation bounds from `prop:arrwindow`, now stated
for the hitting-time distribution of the canonical infinite noisy recursion. -/
theorem escapeTimeProbabilityWindow
    {p : LoopParams} (model : DriftModelAssumptions p)
    (ss : SmallStepAssumption p) (threshold : ThresholdAssumption p)
    {rho L : ℝ} (hrho : 0 ≤ rho) (hrhoCure : rho < cureThreshold p)
    (hcoop : rho ≤ 2 * p.c * (1 - p.c))
    (weighted : WeightedThresholdAssumption p rho)
    (hL : IsLipschitzConstantOn (weightedBarrierIntegrand p rho) L
      0 weighted.βdagger) :
    (∀ delta : ℝ, 0 < delta → ∃ T : ℕ,
      (((-upwardStrategyCost weighted - delta : ℝ) : EReal) ≤
        liminf
          (fun sigma : ℝ ↦ gaussianEscapeTimeLogRate weighted T sigma)
          (nhdsWithin 0 (Ioi (0 : ℝ))))) ∧
    (∀ T : ℕ,
      limsup (fun sigma : ℝ ↦ gaussianEscapeTimeLogRate weighted T sigma)
          (nhdsWithin 0 (Ioi (0 : ℝ))) ≤
        ((-((2 / (p.α * (1 + 2 * p.α * L))) *
          (∫ b in (0 : ℝ)..weighted.βdagger,
            weightedBarrierIntegrand p rho b)) : ℝ) : EReal)) := by
  obtain ⟨hlower, hupper⟩ := escapeProbabilityWindow model ss threshold
    hrho hrhoCure hcoop weighted hL
  constructor
  · intro delta hdelta
    obtain ⟨T, _hcapturing, hcrossing⟩ := hlower delta hdelta
    exact ⟨T, by simpa only [gaussianEscapeTimeLogRate_eq] using hcrossing⟩
  · intro T
    simpa only [gaussianEscapeTimeLogRate_eq] using hupper T

/-- Finite-horizon survival is a measurable event. -/
theorem measurableSet_gaussianEscapeTime_gt {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    MeasurableSet
      {xi | (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi} := by
  rw [show {xi | (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi} =
      (gaussianEscapeByEvent weighted T sigma)ᶜ by
    ext xi
    simp only [mem_setOf_eq, mem_compl_iff]
    rw [← gaussianEscapeTime_le_iff weighted sigma xi T]
    exact (not_le :
      ¬gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ) ↔
        (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi).symm]
  exact (measurableSet_gaussianEscapeByEvent weighted T sigma).compl

/-- The survival probability of the first saddle-crossing time is one minus the
finite-window crossing probability. -/
theorem standardGaussianSequence_escapeTime_gt {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    standardGaussianSequence
        {xi | (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi} =
      1 - gaussianEscapeProbability weighted T sigma := by
  rw [show {xi | (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi} =
      (gaussianEscapeByEvent weighted T sigma)ᶜ by
    ext xi
    simp only [mem_setOf_eq, mem_compl_iff]
    rw [← gaussianEscapeTime_le_iff weighted sigma xi T]
    exact (not_le :
      ¬gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ) ↔
        (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi).symm]
  rw [measure_compl (measurableSet_gaussianEscapeByEvent weighted T sigma)
    (measure_ne_top standardGaussianSequence _)]
  rw [measure_univ, standardGaussianSequence_escapeByEvent]

/-- The extended-natural first-crossing time embedded in the nonnegative extended
reals. -/
def gaussianEscapeTimeENNReal {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ)
    (xi : GaussianNoisePath) : ℝ≥0∞ :=
  ENat.toENNReal (show ℕ∞ from gaussianEscapeTime weighted sigma xi)

/-- An extended natural is the sum of the indicators of its strict natural
sublevels. -/
theorem enatToENNReal_eq_tsum_lt (t : ℕ∞) :
    ENat.toENNReal t =
      ∑' n : ℕ, if (n : ℕ∞) < t then (1 : ℝ≥0∞) else 0 := by
  induction t using ENat.recTopCoe with
  | top =>
      simp only [ENat.toENNReal_top, ENat.coe_lt_top, if_true]
      exact (ENNReal.tsum_const_eq_top_of_ne_zero one_ne_zero).symm
  | coe k =>
      rw [ENat.toENNReal_coe]
      rw [tsum_eq_sum (s := Finset.range k)]
      · calc
          (k : ℝ≥0∞) = ∑ _n ∈ Finset.range k, (1 : ℝ≥0∞) := by simp
          _ = ∑ n ∈ Finset.range k,
              if n < k then (1 : ℝ≥0∞) else 0 := by
            apply Finset.sum_congr rfl
            intro n hn
            rw [if_pos (Finset.mem_range.mp hn)]
          _ = ∑ n ∈ Finset.range k,
              if (n : ℕ∞) < (k : ℕ∞) then (1 : ℝ≥0∞) else 0 := by
            simp only [ENat.coe_lt_coe]
      · intro n hn
        simp only [Finset.mem_range, not_lt] at hn
        simp [hn]

/-- The extended mean first-crossing time of the canonical noisy recursion.
Infinite crossing times contribute `top`, as required for an unconditional
mean first-passage time rather than a conditional mean. -/
def meanGaussianEscapeTime {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ) : ℝ≥0∞ :=
  ∫⁻ xi, gaussianEscapeTimeENNReal weighted sigma xi
    ∂standardGaussianSequence

/-- Exact tail-sum representation of the mean first-passage time.  This is
the summation interface used by geometric restart bounds. -/
theorem meanGaussianEscapeTime_eq_tsum_survival
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ) :
    meanGaussianEscapeTime weighted sigma =
      ∑' T : ℕ, (1 - gaussianEscapeProbability weighted T sigma) := by
  have hindicator : ∀ T : ℕ,
      (fun xi : GaussianNoisePath ↦
        if (T : ℕ∞) <
            (show ℕ∞ from gaussianEscapeTime weighted sigma xi)
          then (1 : ℝ≥0∞) else 0) =
        {xi | (T : WithTop ℕ) <
          gaussianEscapeTime weighted sigma xi}.indicator (fun _ ↦ 1) := by
    intro T
    funext xi
    by_cases hxi : (T : WithTop ℕ) <
        gaussianEscapeTime weighted sigma xi
    · have hxi' : (T : ℕ∞) <
          (show ℕ∞ from gaussianEscapeTime weighted sigma xi) := hxi
      rw [if_pos hxi']
      have hmem : xi ∈ {xi : GaussianNoisePath |
          (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi} := hxi
      exact (indicator_of_mem hmem (fun _ ↦ (1 : ℝ≥0∞))).symm
    · have hxi' : ¬(T : ℕ∞) <
          (show ℕ∞ from gaussianEscapeTime weighted sigma xi) := hxi
      rw [if_neg hxi']
      have hmem : xi ∉ {xi : GaussianNoisePath |
          (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi} := hxi
      exact (indicator_of_notMem hmem (fun _ ↦ (1 : ℝ≥0∞))).symm
  rw [meanGaussianEscapeTime]
  conv_lhs =>
    enter [2, xi]
    rw [gaussianEscapeTimeENNReal, enatToENNReal_eq_tsum_lt]
  rw [lintegral_tsum]
  · congr 1
    funext T
    rw [hindicator T]
    rw [lintegral_indicator_const
      (measurableSet_gaussianEscapeTime_gt weighted T sigma)]
    rw [one_mul, standardGaussianSequence_escapeTime_gt]
  · intro T
    rw [hindicator T]
    exact (measurable_const.indicator
      (measurableSet_gaussianEscapeTime_gt weighted T sigma)).aemeasurable

/-- Any summable pointwise majorant of the survival probabilities bounds the
mean escape time. -/
theorem meanGaussianEscapeTime_le_tsum_of_survival_le
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ)
    (majorant : ℕ → ℝ≥0∞)
    (hmajorant : ∀ T,
      1 - gaussianEscapeProbability weighted T sigma ≤ majorant T) :
    meanGaussianEscapeTime weighted sigma ≤ ∑' T, majorant T := by
  rw [meanGaussianEscapeTime_eq_tsum_survival]
  exact ENNReal.tsum_le_tsum hmajorant

/-- A per-step geometric survival estimate yields the corresponding geometric
bound on the mean.  A block-restart proof can use the preceding general lemma
with its blockwise majorant. -/
theorem meanGaussianEscapeTime_le_inv_one_sub_of_survival_le_geometric
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (sigma : ℝ) (q : ℝ≥0∞)
    (hgeometric : ∀ T,
      1 - gaussianEscapeProbability weighted T sigma ≤ q ^ T) :
    meanGaussianEscapeTime weighted sigma ≤ (1 - q)⁻¹ := by
  calc
    meanGaussianEscapeTime weighted sigma ≤ ∑' T : ℕ, q ^ T :=
      meanGaussianEscapeTime_le_tsum_of_survival_le
        weighted sigma (fun T ↦ q ^ T) hgeometric
    _ = (1 - q)⁻¹ := ENNReal.tsum_geometric q

/-- A finite-horizon survival probability gives the elementary lower bound
`T * P(tau > T) ≤ E[tau]`.  This is the expectation bridge used by the
persistence half of the Arrhenius theorem. -/
theorem horizon_mul_survival_le_meanGaussianEscapeTime
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) (T : ℕ) (sigma : ℝ) :
    (T : ℝ≥0∞) * (1 - gaussianEscapeProbability weighted T sigma) ≤
      meanGaussianEscapeTime weighted sigma := by
  let survival : Set GaussianNoisePath :=
    {xi | (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi}
  have hsurvival : survival = (gaussianEscapeByEvent weighted T sigma)ᶜ := by
    ext xi
    simp only [survival, mem_setOf_eq, mem_compl_iff]
    rw [← gaussianEscapeTime_le_iff weighted sigma xi T]
    exact (not_le :
      ¬gaussianEscapeTime weighted sigma xi ≤ (T : WithTop ℕ) ↔
        (T : WithTop ℕ) < gaussianEscapeTime weighted sigma xi).symm
  have hsurvivalMeasurable : MeasurableSet survival := by
    rw [hsurvival]
    exact (measurableSet_gaussianEscapeByEvent weighted T sigma).compl
  have hsurvivalMeasure :
      standardGaussianSequence survival =
        1 - gaussianEscapeProbability weighted T sigma := by
    rw [hsurvival, measure_compl
      (measurableSet_gaussianEscapeByEvent weighted T sigma)
      (measure_ne_top standardGaussianSequence _)]
    rw [measure_univ, standardGaussianSequence_escapeByEvent]
  have hpointwise :
      survival.indicator (fun _ ↦ (T : ℝ≥0∞)) ≤
        gaussianEscapeTimeENNReal weighted sigma := by
    intro xi
    by_cases hxi : xi ∈ survival
    · rw [indicator_of_mem hxi]
      have htime :
          (T : ℕ∞) ≤
            (show ℕ∞ from gaussianEscapeTime weighted sigma xi) := by
        change (T : WithTop ℕ) ≤ gaussianEscapeTime weighted sigma xi
        exact hxi.le
      exact ENat.toENNReal_mono htime
    · rw [indicator_of_notMem hxi]
      exact bot_le
  calc
    (T : ℝ≥0∞) * (1 - gaussianEscapeProbability weighted T sigma) =
        (T : ℝ≥0∞) * standardGaussianSequence survival := by
      rw [hsurvivalMeasure]
    _ = ∫⁻ xi, survival.indicator (fun _ ↦ (T : ℝ≥0∞)) xi
          ∂standardGaussianSequence := by
      rw [lintegral_indicator_const hsurvivalMeasurable]
    _ ≤ ∫⁻ xi, gaussianEscapeTimeENNReal weighted sigma xi
          ∂standardGaussianSequence :=
      lintegral_mono hpointwise
    _ = meanGaussianEscapeTime weighted sigma := rfl

#print axioms standardGaussianSequence_map_prefix
#print axioms measurable_gaussianPrefix
#print axioms standardGaussianSequence_map_tail
#print axioms measurable_gaussianTail
#print axioms standardGaussianSequence_tail_preimage
#print axioms gaussianNoisyOrbit_isControlled
#print axioms continuous_gaussianNoisyOrbit
#print axioms stronglyMeasurable_gaussianNoisyOrbit
#print axioms gaussianNoisyOrbit_adapted
#print axioms gaussianNoisyOrbit_eq_finiteControlledOrbit
#print axioms le_runningMax_iff
#print axioms continuous_policyRunningMax_finiteControlledOrbit
#print axioms continuous_policyRunningMax_gaussianNoisyOrbit
#print axioms measurableSet_gaussianEscapeEvent
#print axioms measurableSet_gaussianEscapeByEvent
#print axioms gaussianPrefix_preimage_escapeEvent
#print axioms standardGaussianSequence_escapeByEvent
#print axioms gaussianEscapeTime_isStoppingTime
#print axioms gaussianEscapeTime_le_iff
#print axioms standardGaussianSequence_escapeTime_le
#print axioms gaussianEscapeTimeProbability_eq
#print axioms gaussianEscapeTimeLogRate_eq
#print axioms escapeTimeProbabilityWindow
#print axioms measurableSet_gaussianEscapeTime_gt
#print axioms standardGaussianSequence_escapeTime_gt
#print axioms enatToENNReal_eq_tsum_lt
#print axioms meanGaussianEscapeTime_eq_tsum_survival
#print axioms meanGaussianEscapeTime_le_tsum_of_survival_le
#print axioms meanGaussianEscapeTime_le_inv_one_sub_of_survival_le_geometric
#print axioms horizon_mul_survival_le_meanGaussianEscapeTime

end

end CivicAlignment.PaperII
