/-
Copyright (c) 2026 Daniel Hofheinz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Hofheinz
-/
import CivicAlignment.PaperII.ArrheniusSaddle

/-!
# Paper II: reverse-passage node and overshoot diagnostic

The zero-margin uphill feedback uses control `u = -2g` while the weighted
gradient `g` is negative.  Before projection its policy update is therefore
`beta' = beta - alpha g`, while the stock still follows its forward recursion.
This file records the exact linearization of that reverse-passage map at the
weighted saddle.

The sign of its discriminant is a precise local node/focus diagnostic.  It is
not an optimal-control theorem and, in particular, does not identify either
quasipotential or imply their equality or strict separation.
-/

namespace CivicAlignment.PaperII

open Set

noncomputable section

/-- The unclipped reverse-passage map generated by the feedback control
`u = -2g`. -/
def civicWeightedReversePassageMap
    (p : LoopParams) (rho : ℝ) (x : LoopState) : LoopState :=
  (x.1 - p.α * civicWeightedGradient p rho x.1 x.2,
    p.stockStep x.1 x.2)

/-- Applying control `-2g` in the original controlled recursion gives the
projected reverse-passage policy input exactly. -/
theorem controlledCivicWeightedStep_doubling_eq
    (p : LoopParams) (rho : ℝ) (x : LoopState) :
    controlledCivicWeightedStep p rho
        (-2 * civicWeightedGradient p rho x.1 x.2) x =
      (LoopParams.clipUnit
          (x.1 - p.α * civicWeightedGradient p rho x.1 x.2),
        p.stockStep x.1 x.2) := by
  simp only [controlledCivicWeightedStep]
  congr 2
  ring

/-- The exact reverse-passage linearization at an interior state. -/
def weightedReversePassageJacobian
    (p : LoopParams) (rho beta D : ℝ) : LoopJacobian where
  a := 1 + 2 * p.α * p.c ^ 2 * D
  b := -p.α * (2 * p.c * (1 - p.c * beta) - rho)
  cJ := p.sSlope beta * D
  d := p.s beta

/-- The reverse-passage discriminant written without matrix notation. -/
def reversePassageDiscriminantAtRate
    (p : LoopParams) (rho beta D alpha : ℝ) : ℝ :=
  (1 + 2 * alpha * p.c ^ 2 * D - p.s beta) ^ 2 -
    4 * alpha * (2 * p.c * (1 - p.c * beta) - rho) *
      p.sSlope beta * D

/-- The matrix discriminant is exactly the displayed sign diagnostic. -/
theorem weightedReversePassageJacobian_discriminant
    (p : LoopParams) (rho beta D : ℝ) :
    (weightedReversePassageJacobian p rho beta D).discriminant =
      reversePassageDiscriminantAtRate p rho beta D p.α := by
  simp only [LoopJacobian.discriminant, weightedReversePassageJacobian,
    reversePassageDiscriminantAtRate]
  ring

/-- The same diagnostic is a literal quadratic polynomial in the adaptation
rate. -/
theorem reversePassageDiscriminantAtRate_eq_quadratic
    (p : LoopParams) (rho beta D alpha : ℝ) :
    reversePassageDiscriminantAtRate p rho beta D alpha =
      (2 * p.c ^ 2 * D) ^ 2 * alpha ^ 2 +
      (2 * (2 * p.c ^ 2 * D) * (1 - p.s beta) -
          4 * (2 * p.c * (1 - p.c * beta) - rho) *
            p.sSlope beta * D) * alpha +
      (1 - p.s beta) ^ 2 := by
  simp only [reversePassageDiscriminantAtRate]
  ring

/-- The local reverse-passage modes are real exactly on the nonnegative side
of the explicit discriminant. -/
def ReversePassageIsNodal
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) : Prop :=
  0 ≤ reversePassageDiscriminantAtRate p rho weighted.βdagger
    (p.stationaryStock weighted.βdagger) p.α

/-- A negative reverse-passage discriminant is the discrete-time local
overshoot regime. -/
def ReversePassageIsOscillatory
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) : Prop :=
  reversePassageDiscriminantAtRate p rho weighted.βdagger
    (p.stationaryStock weighted.βdagger) p.α < 0

/-- The nodal and oscillatory regimes are exact complements. -/
theorem reversePassage_nodal_iff_not_oscillatory
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) :
    ReversePassageIsNodal weighted ↔
      ¬ReversePassageIsOscillatory weighted := by
  exact not_lt.symm

/-- Every fixed-rate configuration lies in exactly one of the two local
reverse-passage regimes. -/
theorem reversePassage_nodal_or_oscillatory
    {p : LoopParams} {rho : ℝ}
    (weighted : WeightedThresholdAssumption p rho) :
    ReversePassageIsNodal weighted ∨
      ReversePassageIsOscillatory weighted := by
  exact le_or_gt 0 _

#print axioms controlledCivicWeightedStep_doubling_eq
#print axioms weightedReversePassageJacobian_discriminant
#print axioms reversePassageDiscriminantAtRate_eq_quadratic
#print axioms reversePassage_nodal_iff_not_oscillatory
#print axioms reversePassage_nodal_or_oscillatory

end

end CivicAlignment.PaperII
